### ISSUE TITLE
MEN002 with two severities 

### ISSUE THREAD

**Issue by JKamsker** [menees/Analyzers#3]
I want 2 severities for MEN002 Line is too long:
80 characters: Warn - Consider splitting line
120 characters:  Error - Split lines, otherwise the code won't compile.

Is this possible with the current solution?

**Comment by menees** [comment]
It's not possible with the current release, but it's an interesting suggestion. I'll leave this issue open and try to get this into a future release.

**Comment by menees** [comment]
I added a new MEN002A rule in release 3.0.6 that's disabled by default. You'll need to enable it via a .ruleset or .editorconfig file, and you'll need set the new NotifyLineColumns (e.g., 80) to be less than your MaxLineColumns (e.g., 120) in Menees.Analyzers.Settings.xml.

Also, MEN002 uses Warning severity by default, so for your scenario you'll want to configure it as Error. Similarly, MEN002A uses Info severity by default, so you'll want to configure it as Warning.
