### ISSUE TITLE
Support AllowLongUriLines for comments starting with ///

### ISSUE THREAD

**Issue by gaurav137** [menees/Analyzers#4]
In our codebase <summary> style comments begin with /// so if the same contains a URI then AllowLongUriLines was not working for it. Eg:

```*.cs
/// <summary>
/// Current version status of VMware Tools running in the guest operating system.
/// https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.GuestInfo.ToolsVersionStatus.html.
/// </summary>
```

I can help contribute the change to allow /// but not sure how to raise a pull request. Didn't see any contributions guidance. @menees please let me know if you could add support for the same or how I could raise a PR.

![image](https://user-images.githubusercontent.com/39692417/177253278-d23cdc77-8e9c-4296-af0f-70c41f6fddf4.png)

**Comment by gaurav137** [comment]
#5 #

**Comment by menees** [comment]
Thanks! I implemented this [a slightly different way](https://github.com/menees/Analyzers/blob/a567800e5ce6e26e51fe12ad25b2bcf0ec7909bd/src/Menees.Analyzers/Men002LineTooLong.cs#L153) to allow any number of leading '/' and to support any number of '*' in `/* */`. It's in [release 3.0.7](https://github.com/menees/Analyzers/releases/tag/v3.0.7).
