### ISSUE TITLE
FileRegex based file exclusion not honored for MEN002

### ISSUE THREAD

**Issue by gaurav137** [menees/Analyzers#6]
We generate code with file names ending with codegen.cs and wanted to exclude MEN002 (Line is too long) from being applied to such files. But looks like the file exclusion is not being checked for similar to how its being checked for in MEN008 in the [HandleSyntaxTree](https://github.com/menees/Analyzers/blob/cbd8b0baf4d2976e3fca5260394f95f537fe6dd2/src/Menees.Analyzers/Men008FileNameShouldMatchType.cs#L122) method.

**Comment by gaurav137** [comment]
#5

**Comment by menees** [comment]
The exclusion patterns from MEN008 aren't applicable to MEN002 or other general rules. The TypeFileNameExclusions don't mean "ignore this file for all analyzers". They mean "don't expect these file names to match the name of the contained type for MEN008."

In [release 3.0.7](https://github.com/menees/Analyzers/releases/tag/v3.0.7) I added support for an AnalyzeFileNameExclusions section in Menees.Analyzers.Settings.xml to support custom code-gen file name patterns. It defaults to the following:

``` XML
<AnalyzeFileNameExclusions>
  <FileName>GeneratedCode.cs</FileName>
  <FileRegex>\.(designer|generated|codegen)\.cs$</FileRegex>
</AnalyzeFileNameExclusions>
```

Prior to v3.0.7, it ignored:
* file names like *.designer.cs
* files containing an [`// <auto-generated />` comment header](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/57821a1c4d014e8d80b3e236ff444e0e30d8a112/documentation/SA1633.md#examples) (like StyleCop Analyzers)
* types attributed with the [GeneratedCodeAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute)

Now in v3.0.7+, you can set custom file name exclusion patterns if needed. However, I made the default exclusions handle the case you reported (.codegen.cs) and the other cases I've seen (.designer.cs and .generated.cs).
