### ISSUE TITLE
 Analyzer 'Menees.Analyzers.Men014PreferTryGetValue' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.

### ISSUE THREAD

**Issue by SvetaSliusar** [menees/Analyzers#7]
Visual Studio 2022
Menees.Analyzers Version 3.0.7

The same issue for Menees.Analyzers.Men013UseUtcTime, Menees.Analyzers.Men003MethodTooLong, Menees.Analyzers.Men004PropertyAccessorTooLong, Menees.Analyzers.Men011AlignUsingDirectives, Menees.Analyzers.Men005FileTooLong, Menees.Analyzers.Men002LineTooLong

**Comment by menees** [comment]
How unfortunate. Sorry. Thanks for letting me know. This should be fixed in [v3.0.8](https://github.com/menees/Analyzers/releases/tag/v3.0.8).
